apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePUllSecrets:
        - name: regcred
      containers:
        - name: demo
          image: vishal09taware/myapp:PLACEHOLDER
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
