apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePUllSecrets:
        - name: regcred
      containers:
        - name: demo
          image: "vishal09taware/myapp:39266d57c5c4b77b7ee5a9d28b8d065be500eaa6"
          ports:
            - containerPort: 8080
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePUllSecrets:
        - name: regcred
      containers:
        - name: demo
          image: "vishal09taware/myapp:e5d4c47f1b01fd908ccaa80da933201569176a16"
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args: ["python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"]
          imagePullPolicy: IfNotPresent
